version: '3'
services:
  historian:
    build: 
      context: ./historian
    ports:
    - "5000:5000"
  aggregator:
    build: 
      context: ./aggregator
    ports:
    - "36768:5000"
    environment: 
      TEMPHISTORIAN: http://historian:5000