// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ServiceClients
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;

    /// <summary>
    /// Extension methods for Historian.
    /// </summary>
    public static partial class HistorianExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='deviceId'>
            /// </param>
            /// <param name='datapointId'>
            /// </param>
            /// <param name='timestamp'>
            /// </param>
            /// <param name='value'>
            /// </param>
            public static double? AddDeviceData(this IHistorian operations, string deviceId, string datapointId = default(string), DateTime? timestamp = default(DateTime?), double? value = default(double?))
            {
                return Task.Factory.StartNew(s => ((IHistorian)s).AddDeviceDataAsync(deviceId, datapointId, timestamp, value), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='deviceId'>
            /// </param>
            /// <param name='datapointId'>
            /// </param>
            /// <param name='timestamp'>
            /// </param>
            /// <param name='value'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<double?> AddDeviceDataAsync(this IHistorian operations, string deviceId, string datapointId = default(string), DateTime? timestamp = default(DateTime?), double? value = default(double?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.AddDeviceDataWithHttpMessagesAsync(deviceId, datapointId, timestamp, value, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
